export const MEMENTO_PROMPTS: string[] = [
  "In 100 years, no one will remember your name or your failures. Do the thing.",
  "The #1 regret of the dying: I wish I'd lived my own life, not the one others expected.",
  "Would 80-year-old you respect what you're doing right now?",
  "Tomorrow is not guaranteed. You know this. Act like it.",
  "Rachel is here today. Your parents are here today. That's not permanent.",
  "The gap between who you are and who you want to be closes with today's decisions.",
  "Memento mori. You will die. So will everyone you love. Use the time.",
  "Most people spend their lives preparing to live.",
  "Every hour you burn on noise is an hour your future self will never recover.",
  "The clock is not paused while you scroll.",
  "You're not tired. You're avoiding. There's a difference.",
  "One day you'll ask for more time. Today you have it.",
  "The people who change the world aren't more gifted — they just refused to waste the days they had.",
  "Fear the deathbed regret more than today's discomfort.",
  "Compress your timelines. The year ahead will feel like a week in 20 years.",
  "Death is the most democratic fact in existence. Plan around it.",
  "Your parents are aging. Build while they can watch.",
  "This moment is already gone. The next one is yours to use.",
  "Bezos asked: at 80, will I regret not having tried? That's the only filter that matters.",
  "The urgency you feel when you nearly miss a flight — that's how you should feel every morning.",
];
